version: "3.7"

services:

  webserver:
    image: nginx:alpine
    container_name: ${APP_NAME}-webserver
    working_dir: /app
    depends_on:
      - phpfpm
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ../:/app
      - ./nginx/sites-enabled:/etc/nginx/conf.d/
      - ./nginx/local.nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/custom/
      - ./ssl/:/etc/ssl/
      - phpsocket:/var/run/
      - ${LOGS_FOLDER}/nginx:/var/log/nginx/
    sysctls:
      net.ipv4.ip_unprivileged_port_start: '0'
    user: ${HOST_UID}:${HOST_GID}
    restart: always
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  phpfpm:
    image: devilbox/php-fpm:8.0-work
    container_name: ${APP_NAME}-phpfpm
    working_dir: /app
    environment:
      - NEW_UID=${HOST_UID}
      - NEW_GID=${HOST_GID}
      - DEBUG_ENTRYPOINT=${DOCKER_PHPFPM_DEBUG_ENTRYPOINT}
      - DOCKER_LOGS=${DOCKER_PHPFPM_DOCKER_LOGS}
      - DISABLE_MODULES=${DOCKER_PHPFPM_DISABLE_MODULES}
      - TIMEZONE=${TIMEZONE}
      - TZ=${TIMEZONE}
    volumes:
      - ../:/app
      - ./php-fpm/default/phpfpm.conf:/usr/local/etc/php-fpm.conf
      - ./php-fpm/local.phpfpm.conf:/etc/php-fpm-custom.d/phpfpm.conf
      - ./php-fpm/local.php.ini:/etc/php-fpm-custom.d/php.ini
      - phpsocket:/var/run
      - ${LOGS_FOLDER}/php:/var/log/php
    restart: always
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  database:
    image: postgres:13-alpine
    container_name: ${APP_NAME}-database
    ports:
      - 5000:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGTZ=${TIMEZONE}
      - TZ=${TIMEZONE}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ${LOGS_FOLDER}/postgresql:/logs:z
    restart: always
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  cache:
    container_name: ${APP_NAME}-cache
    image: bitnami/redis
    restart: always
    command: "/opt/bitnami/scripts/redis/run.sh --logfile \"/bitnami/log/redis.log\""
    volumes:
      - ${LOGS_FOLDER}/redis:/bitnami/log/
      - cache-data:/bitnami/redis/data
    environment:
      - REDIS_AOF_ENABLED=yes
      - DISABLE_COMMANDS=CONFIG
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=${TIMEZONE}
    logging:
      options:
        max-size: "50m"
        max-file: "3"

volumes:
  db-data:
  cache-data:
  letsencrypt:
  phpsocket:
